export const FIREBASE_PROVIDER_TOKEN_NAME = 'FIREBASE_ADMIN';
export const REKOGNITION_PROVIDER_TOKEN_NAME = 'REKOGNITION_CLIENT';

export const USER_CONSTANTS = {
    ID_MAX_LENGTH: 128,
    USERNAME_MAX_LENGTH: 32,
    FIRSTNAME_MAX_LENGTH: 32,
    LASTNAME_MAX_LENGTH: 32,
    EMAIL_MAX_LENGTH: 64,
    PHONE_NUMBER_MAX_LENGTH: 64,
    PROFILE_PIC_LINK_MAX_LENGTH: 64,
};