export const USER_PK_CONSTRAINT_NAME = 'PK_USER';
export const USERNAME_CONSTRAINT_NAME = 'UQ_USER_USERNAME';
export const FOLLOWS_PK_CONSTRAINT_NAME = 'PK_FOLLOWS';
export const FOLLOWINGID_FOLLOWS_CONSTRAINT_NAME = 'FK_FOLLOWS_FOLLOWING_ID';
export const FOLLOWEDID_FOLLOWS_CONSTRAINT_NAME = 'FK_FOLLOWS_FOLLOWED_ID';