export const FIREBASE_PROVIDER_TOKEN = 'FIREBASE_ADMIN';
export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY';
export const PHOTO_REPOSITORY_TOKEN = 'PHOTO_REPOSITORY';
export const REKOGNITION_PROVIDER_TOKEN = 'REKOGNITION_CLIENT';
export const S3_PROVIDER_TOKEN = 'S3_CLIENT';
export const REDIS_PROVIDER_WORKER_TOKEN = 'REDIS_CLIENT_WORKER';
export const REDIS_PROVIDER_LISTENER_TOKEN = 'REDIS_CLIENT_LISTENER';