export const FIREBASE_PROVIDER_TOKEN = 'FIREBASE_ADMIN';
export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY';
export const REKOGNITION_PROVIDER_TOKEN = 'REKOGNITION_CLIENT';
export const S3_PROVIDER_TOKEN = 'S3_CLIENT';
export const FRIEND_REPOSITORY_TOKEN = 'FRIEND_REPOSITORY_TOKEN';
