export const USER_ENTITY_CONSTANTS = {
    ID_MAX_LENGTH: 128,
    USERNAME_MAX_LENGTH: 32,
    FIRSTNAME_MAX_LENGTH: 32,
    LASTNAME_MAX_LENGTH: 32,
    EMAIL_MAX_LENGTH: 64,
    PHONE_NUMBER_MAX_LENGTH: 64,
    PROFILE_PIC_OBJ_KEY_MAX_LENGTH: 64,
};

export const DEFAULT_DAILY_UPLOAD_COUNT = 100;